#!/usr/bin/env node
/**
 * Ensures every doc id referenced in sidebars.ts exists as a .md file.
 * Fills gaps with rich stubs so the academy always builds while chapters are authored.
 */
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DOCS = path.resolve(__dirname, '../docs');
const SIDEBARS = path.resolve(__dirname, '../sidebars.ts');

function extractDocIds(src) {
  const ids = new Set();
  const re = /['"]([a-z0-9/-]+)['"]/g;
  let m;
  while ((m = re.exec(src))) {
    const id = m[1];
    if (
      id.includes('/') ||
      ['intro'].includes(id) ||
      id.startsWith('overview') ||
      id.startsWith('architecture') ||
      id.startsWith('tutorials') ||
      id.startsWith('backend') ||
      id.startsWith('frontend') ||
      id.startsWith('database') ||
      id.startsWith('api') ||
      id.startsWith('files') ||
      id.startsWith('security') ||
      id.startsWith('performance') ||
      id.startsWith('sre') ||
      id.startsWith('deployment') ||
      id.startsWith('testing') ||
      id.startsWith('runbooks') ||
      id.startsWith('learning') ||
      id.startsWith('labs') ||
      id.startsWith('quizzes') ||
      id.startsWith('animations') ||
      id.startsWith('glossary') ||
      id.startsWith('scaling')
    ) {
      if (!id.includes('*') && id !== 'autogenerated' && !id.startsWith('files/generated/')) {
        ids.add(id);
      }
    }
  }
  // Always ensure intro
  ids.add('intro');
  return [...ids];
}

function stub(id) {
  const title = id
    .split('/')
    .pop()
    .replace(/-/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase());
  const section = id.split('/')[0];
  return `---
sidebar_label: ${title}
title: ${title}
description: Dhandho Engineering Academy — ${id}
---

# ${title}

:::info Chapter in the living academy
This page is part of the **Dhandho Engineering Academy** curriculum (\`${id}\`).
If you are reading a short stub, a deeper rewrite may still be landing — use linked chapters and the [generated file index](/files/generated/) meanwhile.
:::

## Learning objectives

- Explain **why** this topic exists in DG-ERP / Dhandho
- Trace **where** it lives in the repository
- Name **what breaks** if it is misunderstood in production
- Complete the related lab or quiz before marking yourself “done”

## Why this matters

Dhandho is a multi-tenant, GST-aware ERP for Indian SMEs spanning web and Electron. Every subsystem below either protects tenant isolation, money correctness, tax compliance, or operator sanity at 2am.

## Mental model

\`\`\`mermaid
flowchart TB
  subgraph Surfaces
    W[Web SPA]
    E[Electron]
    M[Mobile]
  end
  Surfaces --> X[Express API]
  X --> P[(PostgreSQL + RLS)]
  X --> A[AuthN / AuthZ]
\`\`\`

## Key concepts

| Concept | In this codebase |
|---|---|
| Tenant isolation | \`tenant_id\` + JWT + RLS |
| Dual deploy | Cloud SaaS + on-prem Electron |
| GST compliance | NIC IRN/EWB, GSTR reports |
| Platform matrix | \`src/platforms/*\` online/offline |

## Where to look in the repo

| Area | Path |
|---|---|
| Server entry | \`server/index.ts\`, \`server/app.ts\` |
| Schema | \`server/pg-db.ts\` |
| Auth | \`server/middleware/auth.ts\`, \`permissions.ts\` |
| Client shell | \`src/App.tsx\`, \`src/api.ts\` |
| Features | \`src/features/*\` |

## Common mistakes

1. Querying without \`tenant_id\`
2. Trusting client-supplied tenant or role
3. Returning raw errors to the browser
4. Putting secrets in \`VITE_*\` variables
5. Editing \`DistributionView\` / giant routes without tests

## Alternatives & trade-offs

| Choice in Dhandho | Alternative | Why not (yet) |
|---|---|---|
| Hand-rolled SQL | Prisma/Drizzle | GST fragments + raw control |
| No React Router | React Router | Tab app + slug entry is simpler |
| Idempotent \`initSchema\` | Flyway/Knex | Solo-team velocity; accept migration pain later |

## Hands-on exercise

1. Clone DG-ERP and run \`npm run dev:all\`
2. Log in as a tenant user and as Super Admin
3. Capture one authenticated request in DevTools → Network
4. Find the matching route file under \`server/routes/\`
5. Write three bullets: purpose, authz rule, tenant predicate

## Debugging exercise

Reproduce a **403** by calling an Admin-only endpoint as Staff. Read \`enforceModulePermissions\` and the role preset. Document the exact check that failed.

## Optimization challenge

Find one N+1 or unbounded \`SELECT\` in the module closest to this chapter. Propose an indexed query or pagination change with before/after complexity.

## Quiz

1. What three layers enforce multi-tenancy?
2. Where is the live role hydrated on each request?
3. Name one accepted security risk documented in the academy.

<details>
<summary>Answers</summary>

1. Explicit \`WHERE tenant_id\`, JWT-scoped tenant, Postgres RLS safety net.
2. Global JWT middleware in \`server/app.ts\` (+ \`authCache\`), not stale JWT claims alone.
3. Examples: JWT in \`localStorage\`; \`xlsx\` CVE accepted; RLS not forced on pool owner.

</details>

## Related pages

- [Welcome](/)
- [Architecture](/architecture/system-overview)
- [Security](/security/threat-model)
- [Labs](/labs)
- [File Walkthrough](/files)
- [Runbooks](/runbooks)
- [Quizzes](/quizzes)
- [Animations](/animations)
- [Glossary](/glossary)

## Further reading

- Repo \`DEVELOPER.md\` and \`docs/architecture.md\`
- Academy section: **${section}**
`;
}

function main() {
  const src = fs.readFileSync(SIDEBARS, 'utf8');
  const ids = extractDocIds(src);
  let created = 0;
  for (const id of ids) {
    const md = path.join(DOCS, `${id}.md`);
    const mdx = path.join(DOCS, `${id}.mdx`);
    if (fs.existsSync(md) || fs.existsSync(mdx)) continue;
    fs.mkdirSync(path.dirname(md), {recursive: true});
    fs.writeFileSync(md, stub(id));
    created++;
    console.log('stub', id);
  }
  console.log(`Checked ${ids.length} ids; created ${created} stubs`);
}

main();
