import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  academySidebar: [
    'intro',
    {
      type: 'category',
      label: '01 · Project Overview',
      collapsed: false,
      items: [
        'overview/business-goals',
        'overview/product-domain',
        'overview/tech-stack',
        'overview/folder-structure',
        'overview/personas-and-roles',
        'overview/ai-origin-assumptions',
      ],
    },
    {
      type: 'category',
      label: '02 · Architecture',
      items: [
        'architecture/system-overview',
        'architecture/request-lifecycle',
        'architecture/multi-tenancy',
        'architecture/four-surfaces',
        'architecture/design-decisions',
        'architecture/mobile-service-seats',
        'architecture/dependency-graph',
        'architecture/component-tree',
        'architecture/error-flow',
        'architecture/business-workflows',
      ],
    },
    {
      type: 'category',
      label: '03 · Getting Started',
      items: [
        'tutorials/day-1-onboarding',
        'tutorials/local-setup',
        'tutorials/first-feature',
        'tutorials/mental-models',
      ],
    },
    {
      type: 'category',
      label: '04 · Backend Engineering',
      items: [
        'backend/overview',
        'backend/app-bootstrap',
        'backend/middleware-stack',
        'backend/auth-middleware',
        'backend/permissions',
        'backend/pg-db',
        'backend/utils-catalog',
        'backend/services-nic-api',
        'backend/routes-catalog',
        'backend/patterns',
      ],
    },
    {
      type: 'category',
      label: '05 · Frontend Engineering',
      items: [
        'frontend/overview',
        'frontend/app-shell',
        'frontend/routing',
        'frontend/api-client',
        'frontend/session-state',
        'frontend/features-catalog',
        'frontend/platforms',
        'frontend/i18n',
        'frontend/ui-kit',
        'frontend/patterns',
      ],
    },
    {
      type: 'category',
      label: '06 · Database',
      items: [
        'database/schema-overview',
        'database/erd',
        'database/platform-tables',
        'database/tenant-tables',
        'database/rls',
        'database/queries-and-fragments',
        'database/migrations-strategy',
        'database/performance',
      ],
    },
    {
      type: 'category',
      label: '07 · API Reference',
      items: [
        'api/overview',
        'api/auth',
        'api/products-inventory',
        'api/sales-distribution',
        'api/finance-accounts',
        'api/gst',
        'api/super-admin',
        'api/mobile-onprem',
        'api/conventions',
      ],
    },
    {
      type: 'category',
      label: '08 · File Walkthrough',
      items: [
        'files/index',
        {
          type: 'category',
          label: 'Server Files',
          items: [
            'files/server/index',
            'files/server/app',
            'files/server/pg-db',
            'files/server/middleware-auth',
            'files/server/middleware-permissions',
            'files/server/utils',
            'files/server/routes',
            'files/server/services',
          ],
        },
        {
          type: 'category',
          label: 'Frontend Files',
          items: [
            'files/frontend/index',
            'files/frontend/app',
            'files/frontend/api',
            'files/frontend/features',
            'files/frontend/platforms',
            'files/frontend/lib',
            'files/frontend/components',
          ],
        },
        {
          type: 'category',
          label: 'Root & Infra Files',
          items: [
            'files/infra/index',
            'files/infra/docker',
            'files/infra/ci',
            'files/infra/electron',
            'files/infra/vite',
          ],
        },
        {
          type: 'link',
          label: 'Every Source File (generated index)',
          href: '/files/generated',
        },
      ],
    },
    {
      type: 'category',
      label: '09 · Security',
      items: [
        'security/threat-model',
        'security/authentication',
        'security/authorization',
        'security/owasp',
        'security/secrets',
        'security/headers-and-csp',
        'security/tenant-isolation',
        'security/accepted-risks',
      ],
    },
    {
      type: 'category',
      label: '10 · Performance',
      items: [
        'performance/overview',
        'performance/frontend',
        'performance/backend',
        'performance/database',
        'performance/bundle',
        'performance/caching',
        'performance/bottlenecks',
      ],
    },
    {
      type: 'category',
      label: '11 · SRE & Reliability (deferred)',
      collapsed: true,
      items: [
        'sre/overview',
        'sre/slis-slos',
        'sre/golden-signals',
        'sre/logging',
        'sre/metrics-alerting',
        'sre/disaster-recovery',
        'sre/failure-scenarios',
      ],
    },
    {
      type: 'category',
      label: '12 · Deployment',
      items: [
        'deployment/overview',
        'deployment/docker',
        'deployment/render',
        'deployment/electron',
        'deployment/mobile',
        'deployment/cicd',
        'deployment/env-vars',
      ],
    },
    {
      type: 'category',
      label: '13 · Testing',
      items: [
        'testing/overview',
        'testing/unit',
        'testing/api-integration',
        'testing/e2e',
        'testing/coverage-gates',
        'testing/how-to-add-tests',
      ],
    },
    {
      type: 'category',
      label: '14 · Runbooks',
      items: [
        'runbooks/index',
        'runbooks/auth-failures',
        'runbooks/db-down',
        'runbooks/tenant-suspended',
        'runbooks/gst-api-failures',
        'runbooks/deploy-rollback',
        'runbooks/mobile-sync',
        'runbooks/onprem-license',
      ],
    },
    {
      type: 'category',
      label: '15 · Learning Modules',
      items: [
        'learning/index',
        'learning/module-multitenancy',
        'learning/module-gst',
        'learning/module-distribution',
        'learning/module-authz',
        'learning/module-platforms',
        'learning/interview-bank',
      ],
    },
    {
      type: 'category',
      label: '16 · Quizzes',
      items: [
        'quizzes/index',
        'quizzes/quiz-architecture',
        'quizzes/quiz-security',
        'quizzes/quiz-database',
        'quizzes/quiz-frontend',
      ],
    },
    {
      type: 'category',
      label: 'Labs (deferred)',
      collapsed: true,
      items: [
        'labs/index',
        'labs/lab-tenant-isolation',
        'labs/lab-add-endpoint',
        'labs/lab-offline-queue',
        'labs/lab-gst-math',
        'labs/lab-debug-403',
      ],
    },
    {
      type: 'category',
      label: '17 · Animations & Storyboards',
      items: [
        'animations/index',
        'animations/request-lifecycle',
        'animations/auth-flow',
        'animations/sale-to-warranty',
        'animations/quotation-convert',
        'animations/mobile-offline',
      ],
    },
    {
      type: 'category',
      label: '18 · Glossary & Reference',
      items: ['glossary/index', 'glossary/domain-terms', 'glossary/engineering-terms', 'glossary/india-gst-terms'],
    },
    {
      type: 'category',
      label: '19 · Redesign & Scaling',
      items: ['scaling/overview', 'scaling/when-to-split', 'scaling/redesign-options', 'scaling/tech-debt-register'],
    },
  ],
};

export default sidebars;
